/*
Main program of calculator example.
Simply invoke the parser generated by bison, and then display the output.
*/

#include <stdio.h>
#include "expr.h"
#include <string.h>
#include <stdlib.h>
#include <sys/types.h>

/* Clunky: Declare the parse function generated from parser.bison */
extern int yyparse();

/* Clunky: Declare the result of the parser from parser.bison */
extern struct expr *parser_result;
extern struct expr *partial_result;
extern int arrayIndex;
// struct expr *parser_result[16];
// initialize
extern FILE *yyin;

// Define the symbol table
struct SymbolTable symtab;

static void initialize(char *inputFileName)
{

	yyin = fopen(inputFileName, "r");
	if (yyin == NULL)
	{
		fprintf(stderr, "Error: Could not open file %s\n", inputFileName);
		exit(-1);
	}

	char *outputFileName = strcat(inputFileName, ".out");
	stdout = freopen(outputFileName, "w", stdout);
	if (stdout == NULL)
	{
		fprintf(stderr, "Error: Could not open file %s\n", outputFileName);
		exit(-1);
	}
}

static void finalize()
{

	fclose(yyin);
	fclose(stdout);
	destroyHashTable(&symtab);
}

extern struct expr *parser_array[16];

int main(int argc, char *argv[])
{
	char *fileName = argv[1];
	initialize(fileName);

	// array here
	// if(yyparse()==0) {
	int count = 0;

	if (yyparse() == 0)
	{
		//printf("GLOBAL INDEX IS %d\n", arrayIndex);
		count = arrayIndex - 1;
		while (count >= 0)
		{
			char name[2];
			//printf("\nMAIN PRINT\n");
			printf("Parser Address %p ", parser_array[count]);
			printf("parse successful: ");
			expr_print(parser_array[count]);
			printf("\n");
			printf("evaluates to: %f\n", expr_evaluate(parser_array[count]));
			expr_variable(name, parser_array[count]);
			expr_updateKeyPair(parser_array[count], name, expr_evaluate(parser_array[count]));
			count--;
		}
		return 0;
	}
	else
	{
		printf("parse failed!\n");
		return 1;
	}

	finalize();
}
